flowchart LR
EXT1["Email/SMS Gateway"]
EXT2["Payment/3rd-Party API"]
EXT3["Reporting/BI Tool"]
SYS["ABC<br/>General Domain"]
E0["Admin"]
E1["Customer"]
    E0 -->|Requests/Actions| SYS
    SYS -->|Responses/Notifications| E0
    E1 -->|Requests/Actions| SYS
    SYS -->|Responses/Notifications| E1
    SYS -->|Alerts/Updates| EXT1
    SYS <-->|Secure API Calls| EXT2
    SYS -->|Exported Insights| EXT3