flowchart LR
    subgraph Actors
        direction TB
        A0["Admin"]
        A1["End User"]
        A2["Manager"]
        A3["Analyst"]
    end
    subgraph UseCases
        UC0["tmty"]
    end
    A0 --> UC0
    A1 --> UC0
    A2 --> UC0