flowchart LR
SYS["RetailFlow – Inventory & Sales"]
E0["Admin"]
E1["End User"]
E2["Manager"]
E3["Analyst"]
    E0 -->|interacts| SYS
    SYS -->|response| E0
    E1 -->|interacts| SYS
    SYS -->|response| E1
    E2 -->|interacts| SYS
    SYS -->|response| E2
    E3 -->|interacts| SYS
    SYS -->|response| E3